version: "3"

services:

  rabbit-mq: 
    image: rabbitmq:3-management
    container_name: rabbit-nerdstore-pub
    environment: 
      RABBITMQ_DEFAULT_USER: "nerdstore"
      RABBITMQ_DEFAULT_PASS: "nerdstore"
    ports:
      - "5672:5672"
      - "15672:15672"

  sql-server:
      image: desenvolvedorio/nerdstore-sql-server:latest
      container_name: nerdstore-sql-server
      build: 
          context: ../sql
          dockerfile: ./Dockerfile
      ports:
        - "1433:1433"
      environment:
          SA_PASSWORD: "MeuDB@123"
          ACCEPT_EULA: "Y"   

  web-mvc: 
    image: nerdstore-web-mvc-ecommerce:latest
    container_name: nerdstore-web-mvc-ecommerce
    build: 
      context: ../src
      dockerfile: ./web/NSE.WebApp.MVC/Dockerfile
    ports: 
      - "5203:5203"
      - "7116:7116"
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5203 
    depends_on:
      - api-catalogo


  api-catalogo:
    image: nerdstore-api-catalogo:latest
    container_name: nerdstore-api-catalogo
    build: 
      context: ../src
      dockerfile: ./services/NSE.Catalogo.API/Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5225 
    depends_on:
      - rabbit-mq
      - sql-server